scrape:
  url: "https://documents.gov.lk/view/extra-gazettes/egz.html"

output:
  years_json: "meta_data/years.json"
  doc_metadata_json: "meta_data/doc_metadata.json"

archive:
  archive_location: "~/Desktop/doc-archive"
  g_drive_parent_folder_id: "1gAb9u5B3d_ifUOhBuBQbv_lb5Qu18yF7"


