scrape: # Do not change these
  url: "https://documents.gov.lk/view/extra-gazettes/egz.html"

output: # Do not change these
  years_json: "meta_data/years.json"
  doc_metadata_json: "meta_data/doc_metadata.json"
  upload_results_json: "upload_results/upload_results_" 

archive: # Change on your preference
  archive_location: "~/Desktop/doc-archive" # Local archive location
  g_drive_parent_folder_id: "1gAb9u5B3d_ifUOhBuBQbv_lb5Qu18yF7" # Parent folder ID of the google drive. # 1YL6jhUhkStUl589tSGgLOdiFtHB85sYu

credentials: # Change on your preference
  token_path: /Users/yasandu/Desktop/credentials/token.json # Set your credentials file
  client_secrets_path: /Users/yasandu/Desktop/credentials/credentials.json # Set your credentials file
  
# /Users/yasandu/Desktop/gztarchiver/config.yaml